# Generated by Django 4.0.4 on 2022-11-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('farm_name', models.CharField(max_length=30)),
                ('harrow', models.BooleanField(default=False)),
                ('cultivator', models.BooleanField(default=False)),
                ('rotavator', models.BooleanField(default=False)),
                ('plough', models.BooleanField(default=False)),
                ('paddy_trasher', models.BooleanField(default=False)),
                ('dumping_trailer', models.BooleanField(default=False)),
                ('four_wheel_trailer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_owner', to='Records.farmer')),
            ],
        ),
    ]
