# Generated by Django 4.0.4 on 2022-11-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='cultivator',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='dumping_trailer',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='four_wheel_trailer',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='harrow',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='paddy_trasher',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='plough',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='rotavator',
        ),
        migrations.AddField(
            model_name='tractor',
            name='cultivator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tractor',
            name='dumping_trailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tractor',
            name='four_wheel_trailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tractor',
            name='harrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tractor',
            name='paddy_trasher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tractor',
            name='plough',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tractor',
            name='rotavator',
            field=models.BooleanField(default=False),
        ),
    ]
